/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tailor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tailor */
        post: operations["tailor_api_tailor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_api_me_delete"];
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_me_patch"];
        trace?: never;
    };
    "/api/auth/register/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Signup Code
         * @description Mail the 6-digit code that ``POST /api/auth/register`` requires.
         *
         *     Same response for registered addresses (they get a "you already have an
         *     account" email instead), so it can't be used to check who is registered.
         */
        post: operations["request_signup_code_api_auth_register_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_auth_password_forgot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_auth_password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Verification */
        post: operations["request_verification_api_auth_verify_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Verification */
        post: operations["confirm_verification_api_auth_verify_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Keys */
        get: operations["list_keys_api_keys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Key */
        put: operations["put_key_api_keys__provider__put"];
        post?: never;
        /** Delete Key */
        delete: operations["delete_key_api_keys__provider__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resumes */
        get: operations["list_resumes_api_resumes_get"];
        put?: never;
        /** Create Resume */
        post: operations["create_resume_api_resumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Resume From Pdf */
        post: operations["create_resume_from_pdf_api_resumes_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Manual Resume
         * @description Author a resume in the app: no document to import, no LLM, no key.
         */
        post: operations["create_manual_resume_api_resumes_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{resume_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Resume Content
         * @description Overwrite the resume with edited facts.
         *
         *     Works on imported resumes too: saving turns one into a manually authored
         *     resume. To keep the original, the editor saves a new resume instead.
         */
        put: operations["update_resume_content_api_resumes__resume_id__content_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Resume
         * @description Compile a resume as written — an unsaved draft, or a stored one.
         *
         *     No job description and no model: this is the untailored document, so the
         *     editor can show the real PDF between edits and a user can download their
         *     base resume without spending an LLM call.
         */
        post: operations["preview_resume_api_resumes_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume */
        get: operations["get_resume_api_resumes__resume_id__get"];
        put?: never;
        post?: never;
        /** Delete Resume */
        delete: operations["delete_resume_api_resumes__resume_id__delete"];
        options?: never;
        head?: never;
        /** Rename Resume */
        patch: operations["rename_resume_api_resumes__resume_id__patch"];
        trace?: never;
    };
    "/api/resumes/{resume_id}/tailored": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Tailored Resume
         * @description Keep a tailoring result: as a new resume, or by overwriting this one.
         *
         *     The proposal comes back from the browser, so it is validated against the
         *     stored resume again, exactly as when the model returned it. A resume
         *     edited since it was tailored no longer matches and is refused.
         */
        post: operations["save_tailored_resume_api_resumes__resume_id__tailored_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jds */
        get: operations["list_jds_api_jds_get"];
        put?: never;
        /** Create Jd */
        post: operations["create_jd_api_jds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jds/{jd_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Jd */
        get: operations["get_jd_api_jds__jd_id__get"];
        /** Update Jd */
        put: operations["update_jd_api_jds__jd_id__put"];
        post?: never;
        /** Delete Jd */
        delete: operations["delete_jd_api_jds__jd_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        /** Delete Run */
        delete: operations["delete_run_api_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompile Run */
        post: operations["recompile_run_api_runs__run_id__compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_resume_from_pdf_api_resumes_pdf_post */
        Body_create_resume_from_pdf_api_resumes_pdf_post: {
            /** File */
            file: string;
            /** Name */
            name?: string | null;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
        };
        /** BulletRewrite */
        BulletRewrite: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** CompilerReport */
        CompilerReport: {
            /**
             * Attempted
             * @default true
             */
            attempted: boolean;
            /** Success */
            success: boolean;
            /** Page Count */
            page_count?: number | null;
            /**
             * Text Preview
             * @default
             */
            text_preview: string;
            /** Warnings */
            warnings?: string[];
            /** Log */
            log?: string | null;
        };
        /** DeleteMeRequest */
        DeleteMeRequest: {
            /** Password */
            password: string;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /** Email */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Compiler Available */
            compiler_available: boolean;
            /** Checks */
            checks?: {
                [key: string]: unknown;
            };
        };
        /** JdCreateRequest */
        JdCreateRequest: {
            /** Title */
            title: string;
            /** Content */
            content: string;
        };
        /** JdDetail */
        JdDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** JdListResponse */
        JdListResponse: {
            /** Jds */
            jds?: components["schemas"]["JdSummary"][];
        };
        /** JdResponse */
        JdResponse: {
            jd: components["schemas"]["JdDetail"];
        };
        /** JdSummary */
        JdSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Excerpt
             * @default
             */
            excerpt: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** JdUpdateRequest */
        JdUpdateRequest: {
            /** Title */
            title?: string | null;
            /** Content */
            content?: string | null;
        };
        /** KeyInfo */
        KeyInfo: {
            /** Provider */
            provider: string;
            /** Hint */
            hint: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** KeysResponse */
        KeysResponse: {
            /** Keys */
            keys?: components["schemas"]["KeyInfo"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MailDispatchResponse
         * @description Enumeration-safe result for the mail-sending routes.
         *
         *     ``ok`` is always True for ``forgot`` and the sign-up code: revealing whether
         *     the address had an account would make them an account oracle. ``delivered``
         *     reports only whether the configured transport actually delivers mail, which
         *     is a property of the server, not of the requested address.
         */
        MailDispatchResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Delivered
             * @default false
             */
            delivered: boolean;
        };
        /** OkResponse */
        OkResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** ProviderInfo */
        ProviderInfo: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Default Model
             * @default
             */
            default_model: string;
            /**
             * Needs Key
             * @default true
             */
            needs_key: boolean;
        };
        /** ProvidersResponse */
        ProvidersResponse: {
            /** Providers */
            providers?: components["schemas"]["ProviderInfo"][];
        };
        /** PutKeyRequest */
        PutKeyRequest: {
            /** Api Key */
            api_key: string;
        };
        /** PutKeyResponse */
        PutKeyResponse: {
            /** Provider */
            provider: string;
            /** Hint */
            hint: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Code */
            code?: string | null;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /** ResumeBullet */
        ResumeBullet: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            link?: components["schemas"]["ResumeLink"] | null;
        };
        /** ResumeChange */
        ResumeChange: {
            /** Field Id */
            field_id: string;
            /** Before */
            before: string;
            /** After */
            after: string;
        };
        /** ResumeContentUpdateRequest */
        ResumeContentUpdateRequest: {
            resume: components["schemas"]["ResumeDraft"];
            style?: components["schemas"]["ResumeStyleInput"] | null;
        };
        /** ResumeCreateRequest */
        ResumeCreateRequest: {
            /** Latex */
            latex: string;
            /** Name */
            name?: string | null;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
        };
        /** ResumeCreateResponse */
        ResumeCreateResponse: {
            resume: components["schemas"]["ResumeDetail"];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * ResumeCustomSection
         * @description A section the fixed template does not name: Certifications, Publications…
         *
         *     Deliberately shaped as title + bullets rather than something richer: it
         *     reuses ``ResumeBullet``, so custom content carries stable IDs and tailoring
         *     can rewrite it under exactly the same rules as experience bullets.
         */
        ResumeCustomSection: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Bullets */
            bullets?: components["schemas"]["ResumeBullet"][];
        };
        /** ResumeData */
        ResumeData: {
            identity: components["schemas"]["ResumeIdentity"];
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Experience */
            experience?: components["schemas"]["ResumeExperience"][];
            /** Projects */
            projects?: components["schemas"]["ResumeProject"][];
            /** Education */
            education?: components["schemas"]["ResumeEducation"][];
            /** Skills */
            skills?: components["schemas"]["ResumeSkillCategory"][];
            /** Achievements */
            achievements?: components["schemas"]["ResumeBullet"][];
            /** Custom Sections */
            custom_sections?: components["schemas"]["ResumeCustomSection"][];
        };
        /** ResumeDetail */
        ResumeDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Source Type */
            source_type: string;
            /**
             * Provider
             * @default
             */
            provider: string;
            /**
             * Model
             * @default
             */
            model: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            style: components["schemas"]["ResumeStyle"];
            data: components["schemas"]["ResumeData"];
        };
        /**
         * ResumeDraft
         * @description A resume as typed into the editor, before the server owns it.
         */
        ResumeDraft: {
            identity?: components["schemas"]["ResumeDraftIdentity"];
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Experience */
            experience?: components["schemas"]["ResumeDraftExperience"][];
            /** Projects */
            projects?: components["schemas"]["ResumeDraftProject"][];
            /** Education */
            education?: components["schemas"]["ResumeDraftEducation"][];
            /** Skills */
            skills?: components["schemas"]["ResumeDraftSkillCategory"][];
            /** Achievements */
            achievements?: string[];
            /** Custom Sections */
            custom_sections?: components["schemas"]["ResumeDraftCustomSection"][];
        };
        /** ResumeDraftCustomSection */
        ResumeDraftCustomSection: {
            /**
             * Title
             * @default
             */
            title: string;
            /** Bullets */
            bullets?: string[];
        };
        /** ResumeDraftEducation */
        ResumeDraftEducation: {
            /**
             * Institution
             * @default
             */
            institution: string;
            /**
             * Degree
             * @default
             */
            degree: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Start
             * @default
             */
            start: string;
            /**
             * End
             * @default
             */
            end: string;
            /** Details */
            details?: string[];
        };
        /** ResumeDraftExperience */
        ResumeDraftExperience: {
            /**
             * Role
             * @default
             */
            role: string;
            /**
             * Company
             * @default
             */
            company: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Start
             * @default
             */
            start: string;
            /**
             * End
             * @default
             */
            end: string;
            /** Bullets */
            bullets?: string[];
        };
        /** ResumeDraftIdentity */
        ResumeDraftIdentity: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Location
             * @default
             */
            location: string;
            /** Links */
            links?: components["schemas"]["ResumeDraftLink"][];
        };
        /** ResumeDraftLink */
        ResumeDraftLink: {
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Url
             * @default
             */
            url: string;
        };
        /** ResumeDraftProject */
        ResumeDraftProject: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Url
             * @default
             */
            url: string;
            /** Technologies */
            technologies?: string[];
            /** Bullets */
            bullets?: string[];
        };
        /** ResumeDraftSkillCategory */
        ResumeDraftSkillCategory: {
            /**
             * Category
             * @default
             */
            category: string;
            /** Items */
            items?: string[];
        };
        /** ResumeEducation */
        ResumeEducation: {
            /** Id */
            id: string;
            /** Institution */
            institution: string;
            /** Degree */
            degree: string;
            /**
             * Location
             * @default
             */
            location: string;
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Details */
            details?: string[];
        };
        /** ResumeExperience */
        ResumeExperience: {
            /** Id */
            id: string;
            /** Company */
            company: string;
            /** Role */
            role: string;
            /**
             * Location
             * @default
             */
            location: string;
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Bullets */
            bullets?: components["schemas"]["ResumeBullet"][];
        };
        /** ResumeIdentity */
        ResumeIdentity: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Location
             * @default
             */
            location: string;
            /** Links */
            links?: components["schemas"]["ResumeLink"][];
        };
        /** ResumeLink */
        ResumeLink: {
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /** ResumeListResponse */
        ResumeListResponse: {
            /** Resumes */
            resumes?: components["schemas"]["ResumeSummary"][];
        };
        /** ResumeManualCreateRequest */
        ResumeManualCreateRequest: {
            resume: components["schemas"]["ResumeDraft"];
            /** Name */
            name?: string | null;
            style?: components["schemas"]["ResumeStyleInput"] | null;
        };
        /**
         * ResumePreviewRequest
         * @description Compile a draft as typed, or one stored resume.
         *
         *     Exactly one of ``resume`` / ``resume_id`` is accepted; the route enforces
         *     that pairing so the mistake gets its own error code.
         */
        ResumePreviewRequest: {
            resume?: components["schemas"]["ResumeDraft"] | null;
            /** Resume Id */
            resume_id?: string | null;
            style?: components["schemas"]["ResumeStyleInput"] | null;
        };
        /** ResumePreviewResponse */
        ResumePreviewResponse: {
            /** Pdf Base64 */
            pdf_base64: string;
            /** Page Count */
            page_count?: number | null;
            /**
             * Filename
             * @default resume.pdf
             */
            filename: string;
            /**
             * Latex Source
             * @default
             */
            latex_source: string;
            compiler: components["schemas"]["CompilerReport"];
        };
        /** ResumeProject */
        ResumeProject: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Url
             * @default
             */
            url: string;
            /** Technologies */
            technologies?: string[];
            /** Bullets */
            bullets?: components["schemas"]["ResumeBullet"][];
        };
        /** ResumeRenameRequest */
        ResumeRenameRequest: {
            /** Name */
            name: string;
        };
        /** ResumeResponse */
        ResumeResponse: {
            resume: components["schemas"]["ResumeDetail"];
        };
        /** ResumeSkillCategory */
        ResumeSkillCategory: {
            /** Category */
            category: string;
            /** Items */
            items: string[];
        };
        /**
         * ResumeStyle
         * @description Bounded, server-validated layout hints extracted from a pasted resume.
         *
         *     Only these safe parameters influence the compiled preamble; the rest of the
         *     template stays server-controlled so the locked-template safety model holds.
         */
        ResumeStyle: {
            /**
             * Paper
             * @default a4paper
             */
            paper: string;
            /**
             * Font Size
             * @default 10pt
             */
            font_size: string;
            /**
             * Margin Cm
             * @default 2
             */
            margin_cm: number;
            /** Accent Hex */
            accent_hex?: string | null;
        };
        /**
         * ResumeStyleInput
         * @description Requested layout knobs; ``sanitize_style`` clamps them to the whitelist.
         *
         *     Looser than :class:`ResumeStyle` on purpose — an out-of-range margin or a
         *     ``#RRGGBB`` accent is normalized rather than rejected, because these are
         *     presentation preferences, not facts.
         */
        ResumeStyleInput: {
            /**
             * Paper
             * @default a4paper
             */
            paper: string;
            /**
             * Font Size
             * @default 10pt
             */
            font_size: string;
            /**
             * Margin Cm
             * @default 2
             */
            margin_cm: number;
            /** Accent Hex */
            accent_hex?: string | null;
        };
        /** ResumeSummary */
        ResumeSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Source Type */
            source_type: string;
            /**
             * Provider
             * @default
             */
            provider: string;
            /**
             * Model
             * @default
             */
            model: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** RunCompileResponse */
        RunCompileResponse: {
            /** Pdf Base64 */
            pdf_base64: string;
            /** Page Count */
            page_count?: number | null;
            /**
             * Filename
             * @default tailored-resume.pdf
             */
            filename: string;
            compiler: components["schemas"]["CompilerReport"];
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: string;
            /** Created At */
            created_at?: string | null;
            /**
             * Resume Id
             * @default
             */
            resume_id: string;
            /**
             * Resume Name
             * @default
             */
            resume_name: string;
            /** Jd Id */
            jd_id?: string | null;
            /** Jd Title */
            jd_title?: string | null;
            /**
             * Jd Excerpt
             * @default
             */
            jd_excerpt: string;
            /**
             * Provider
             * @default
             */
            provider: string;
            /**
             * Model
             * @default
             */
            model: string;
            /** Page Count */
            page_count?: number | null;
            /**
             * Repaired
             * @default false
             */
            repaired: boolean;
            proposal?: components["schemas"]["TailorProposal"] | null;
            /** Changes */
            changes?: components["schemas"]["ResumeChange"][];
            /**
             * Unified Diff
             * @default
             */
            unified_diff: string;
            /**
             * Latex Source
             * @default
             */
            latex_source: string;
            /** Warnings */
            warnings?: string[];
        };
        /** RunListResponse */
        RunListResponse: {
            /** Runs */
            runs?: components["schemas"]["RunSummary"][];
        };
        /** RunResponse */
        RunResponse: {
            run: components["schemas"]["RunDetail"];
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: string;
            /** Created At */
            created_at?: string | null;
            /**
             * Resume Id
             * @default
             */
            resume_id: string;
            /**
             * Resume Name
             * @default
             */
            resume_name: string;
            /** Jd Id */
            jd_id?: string | null;
            /** Jd Title */
            jd_title?: string | null;
            /**
             * Jd Excerpt
             * @default
             */
            jd_excerpt: string;
            /**
             * Provider
             * @default
             */
            provider: string;
            /**
             * Model
             * @default
             */
            model: string;
            /** Page Count */
            page_count?: number | null;
            /**
             * Repaired
             * @default false
             */
            repaired: boolean;
        };
        /**
         * SignupCodeRequest
         * @description Ask for a sign-up code to be mailed to ``email``.
         */
        SignupCodeRequest: {
            /** Email */
            email: string;
        };
        /**
         * TailorProposal
         * @description Only plain text is accepted from the model; never LaTeX.
         */
        TailorProposal: {
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Bullet Rewrites */
            bullet_rewrites: components["schemas"]["BulletRewrite"][];
            /** Skills Order */
            skills_order: string[];
        };
        /** TailorRequest */
        TailorRequest: {
            /** Job Description */
            job_description?: string | null;
            /** Jd Id */
            jd_id?: string | null;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /**
             * Compile
             * @default true
             */
            compile: boolean;
            /**
             * Require One Page
             * @default true
             */
            require_one_page: boolean;
            /** Resume Id */
            resume_id: string;
            /**
             * Save Run
             * @default true
             */
            save_run: boolean;
        };
        /** TailorResponse */
        TailorResponse: {
            proposal: components["schemas"]["TailorProposal"];
            /** Changes */
            changes: components["schemas"]["ResumeChange"][];
            /** Unified Diff */
            unified_diff: string;
            /** Latex Source */
            latex_source: string;
            /** Pdf Base64 */
            pdf_base64?: string | null;
            /** Page Count */
            page_count?: number | null;
            /**
             * Filename
             * @default tailored-resume.pdf
             */
            filename: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /**
             * Repaired
             * @default false
             */
            repaired: boolean;
            /** Warnings */
            warnings?: string[];
            compiler: components["schemas"]["CompilerReport"];
            /** Run Id */
            run_id?: string | null;
        };
        /**
         * TailoredResumeSaveRequest
         * @description Keep a tailoring result as resume content.
         */
        TailoredResumeSaveRequest: {
            proposal: components["schemas"]["TailorProposal"];
            /**
             * Mode
             * @enum {string}
             */
            mode: "new" | "overwrite";
            /** Name */
            name?: string | null;
        };
        /** UpdateMeRequest */
        UpdateMeRequest: {
            /** Name */
            name?: string | null;
            /** Default Provider */
            default_provider?: string | null;
            /** Provider Models */
            provider_models?: {
                [key: string]: string | null;
            } | null;
        };
        /**
         * UserOut
         * @description Public account shape; never includes password material or key values.
         */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Default Provider */
            default_provider?: string | null;
            /** Provider Models */
            provider_models?: {
                [key: string]: string;
            };
            /** Created At */
            created_at?: string | null;
            /** Providers With Keys */
            providers_with_keys?: string[];
            /**
             * Email Verified
             * @default false
             */
            email_verified: boolean;
            /**
             * Verification Required
             * @default false
             */
            verification_required: boolean;
        };
        /** UserResponse */
        UserResponse: {
            user: components["schemas"]["UserOut"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    tailor_api_tailor_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TailorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TailorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    delete_me_api_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_api_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_signup_code_api_auth_register_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailDispatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_auth_password_forgot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailDispatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_auth_password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_verification_api_auth_verify_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailDispatchResponse"];
                };
            };
        };
    };
    confirm_verification_api_auth_verify_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersResponse"];
                };
            };
        };
    };
    list_keys_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeysResponse"];
                };
            };
        };
    };
    put_key_api_keys__provider__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PutKeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_key_api_keys__provider__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resumes_api_resumes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeListResponse"];
                };
            };
        };
    };
    create_resume_api_resumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_resume_from_pdf_api_resumes_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_resume_from_pdf_api_resumes_pdf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_manual_resume_api_resumes_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeManualCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_resume_content_api_resumes__resume_id__content_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeContentUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_resume_api_resumes_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumePreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_api_resumes__resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_resume_api_resumes__resume_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_resume_api_resumes__resume_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_tailored_resume_api_resumes__resume_id__tailored_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TailoredResumeSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jds_api_jds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JdListResponse"];
                };
            };
        };
    };
    create_jd_api_jds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JdCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jd_api_jds__jd_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jd_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_jd_api_jds__jd_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jd_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JdUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_jd_api_jds__jd_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jd_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_run_api_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompile_run_api_runs__run_id__compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCompileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
